### PR TITLE
[FEATURE] Multiple IDPs

### PR DESCRIPTION
**Pull request by 4rthem**
Following #99 (which has been reverted):

- Add `idps` configuration node
- Backward compatibility with a single `idp`
- Add idp name in the security token

Thanks to @hhoechtl for the inspiration.

### CODE REVIEW

**Comment by 4rthem** [comment]
I'm sorry I don't have time to fix DI tests as they are not unit-test.

**Comment by guillaumepotier** [comment]
Hi @4rthem,

Thanks for your PR! Here at Wisembly we are currently implementing this bundle with multiple idps (based on #99). We're facing small problems, that seems to be also present in your PR.

It seems that the SP part is not designed for multiple idps. What happens when a provider heavily rely on the metadata (`/saml/metadata/{idp}`)? From my understanding, he won't get, for example, the predefined login url with its configuration (/saml/login/{idp}) but rather the SP harcdoded one in config?

Dunno if I'm clear enough :)

Best

**Comment by 4rthem** [comment]
Hi @guillaumepotier,

I'm afraid you are right. I haven't faced this problem yet.
I'll try to expose different endpoints while keeping the old routes for a single IDP.

**Comment by guillaumepotier** [comment]
On the configuration side, sp routes could be dynamized by provider by adding the `{idp}` variable (example .../saml/metadata/{idp})
Before the creation of the service for each provider by providing the conf ([loadIdentityProviders](https://github.com/hslavich/OneloginSamlBundle/pull/108/files#diff-1742cb14fd653e872d9471a8f0016868R36)) we can do the necessary replacements 

For info, what we have done so far on top of #99 [here](https://github.com/Wisembly/OneloginSamlBundle/commits/multipleidps-withoutidpmapping)

We are quite in a hurry and have successfully tested that with Onelogin, Google Apps and our client, but we still are very interested by your PR ;)

Best

**Comment by 4rthem** [comment]
> On the configuration side, sp routes could be dynamized by provider by adding the {idp} variable (example .../saml/metadata/{idp})

This is exactly what I did :)

There are remaining single routes (`acs` and `logout`) which rely on the session var I've introduced or on the SamlToken. Its quite complicated to setup many login/logout listeners with a single entrypoint in the Security bundle. I guess it could be done by introducing a new major version (BC break).

**Comment by lmerotta** [comment]
Sorry to bother, but is there any news on this ?

**Comment by JamuelStarkey** [comment]
> There are remaining single routes (`acs` and `logout`) which rely on the session var I've introduced or on the SamlToken.

Thanks for your feature.

I'm testing with symfony 4.4 and the session is empty when `attemptAuthentication(Request $request)` is called in SamlListener.php so the the default idp is being called instead of the idp that was selected from the `saml_login_idp` route.  

I must be doing something wrong but for the life of me can't figure out why the session is empty at this point.  I'm sure it's because I don't know enough about symfony.  Any ideas or pointers in getting this working would be appreciated.

**Comment by 4rthem** [comment]
@JamuelStarkey I guess your session is not started because the session cookie is not sent.

You can use the following configuration to allow cookie to be sent (coming from the identity provider POST request):
```yaml
framework:
    session:
        cookie_samesite: none
```

I know this is not recommended for security so keep preventing CSRF attacks.

**Comment by JamuelStarkey** [comment]
@4rthem 

> framework:
>     session:
>         cookie_samesite: none
> ```

Thanks for the idea.  I just tried that and I still end up with an _InvalidArgumentException: Undefined IDP "default"_

Here's my framework config:

```
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: none
```

Previoiusly `cookie_samesite` was set to `lax`.

Anything else you can think of to try or how better to debug?

Thanks again!

**Comment by JamuelStarkey** [comment]
@4rthem Actually I have it partially working now.  I needed to delete my existing SameSite Lax cookie.  And then I am able to authenticate with multiple IDPs.  The one challenge that I'm facing now is that I cannot perform the logout action.  I get the same Undefined IDP "default" exception that I was seeing before.  Is there something different about the logout action as compared to login?

**Comment by Arakmar** [comment]
Hello ! It's working fine on my side (rebased on top of 1.x branch)
I fixed the logout problem, the idpName wasn't serialized with the SamlToken.
Last commit : https://github.com/JeResilieMonContrat-com/OneloginSamlBundle/commits/1.x-multiple-idp

**Comment by pimjansen** [comment]
Hey all, seems like this one is pretty stale at the moment. Maybe time to integrate it on 2.x and resolve the issues?
Anywhere that i can assist?

**Comment by pimjansen** [comment]
@hslavich are you open for this feature? I think it can benefit a lot of people so.

**Comment by hslavich** [comment]
Hi, I'm interested in this feature but there are several conflicts that I should review in order to merge. Could you create a new updated PR?

**Comment by pimjansen** [comment]
> Hi, I'm interested in this feature but there are several conflicts that I should review in order to merge. Could you create a new updated PR?

Will see what i can do! There is another thing that i wonder that should be there though.

Since there are multiple idps, each of those will publish set of attributes. Shouldn't we add some kind of mapping so that the setAttributes on the entity just holds a single source of truth.

Thoughts?

**Comment by ypereirareis** [comment]
**Hi everyone and thanks for your incredible work.**

I'm also interested by this "multiple IDPs" feature....
Waiting a few more days before going with a fork.

Thanks !!

**Comment by Navds** [comment]
Could you please update Readme, I must have missed something because SamlListener::attemptAuthentication always use 'default' idp. I tried both @4rthem and @Arakmar forks

**Comment by Sscorpion9991** [comment]
Hi! We also are interested in the multiple IDPs feature. Could you please resolve the conflicts and release the feature? Thank you.

**Comment by kboumedal** [comment]
> Could you please update Readme, I must have missed something because SamlListener::attemptAuthentication always use 'default' idp. I tried both @4rthem and @Arakmar forks

Hi! Have you found a solution ? I have exactly the same problem

**Comment by Arakmar** [comment]
With my fork you have to configure your firewall like that :
```
security:
  firewalls:
    saml_test:
      pattern: ^/saml/(acs|logout)/test
      saml:
        provider: saml
        idp_name: test
        use_attribute_friendly_name: false
        check_path: /saml/acs/test
        login_path: /saml/login/test
        failure_path: /saml/failure/test
        always_use_default_target_path: false
        authentication_provider: App\Security\Saml\TestAuthenticationProvider
        success_handler: App\Security\Saml\TestAuthenticationSuccessHandler
```

You can also configure a specific sp config for the idp like that :
```
hslavich_onelogin_saml:
  idps:
    test:
          sp:
            NameIDFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'
            entityId: ''
            assertionConsumerService:
              url: ''
              binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
            singleLogoutService:
              url: '%'
              binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
            x509cert: ''
            privateKey: ''
          entityId: ''
          singleSignOnService:
            url: ''
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
          singleLogoutService:
            url: ''
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
          x509cert: ''
```

**Comment by pimjansen** [comment]
@hslavich can you support here as well since i do not think all the forks are good. Maybe with more maintainers or making it OSS or so?

**Comment by Navds** [comment]
> > Could you please update Readme, I must have missed something because SamlListener::attemptAuthentication always use 'default' idp. I tried both @4rthem and @Arakmar forks
> 
> Hi! Have you found a solution ? I have exactly the same problem

I finally switched to LightSaml for an easier time, too bad there is not a single maintained php/symfony saml repository anywhere

**Comment by a-menshchikov** [comment]
Everyone who is going to use Symfony 6 can use a new bundle [nbgrp/onelogin-saml-bundle](https://github.com/nbgrp/onelogin-saml-bundle) with multiple IdP support.

**Pull request closed without merging**
