### PR TITLE
Updatefix

### PR DESCRIPTION
**Pull request by gjhernandez1234**
Symfony 4 and PHP 7.2 compatible

### CODE REVIEW

**Comment by hslavich** [comment]
This bundle is already working with symfony 4 and php 7. Why would you want to use an unreleased version of onelogin saml?

**Comment by gjhernandez1234** [comment]
Because version v2.13 of onelogin/php-saml requires "ext-mcrypt" and in php 7.2 it was REMOVED
http://php.net/manual/en/intro.mcrypt.php

This generates an error when installing the requirements package.

The version 3.0 of php-saml is already in development which already contemplate this REMOVED of mcrypt

**Comment by hslavich** [comment]
Ok , maybe I should wait for php-saml 3 release since it's not a good idea attach this to a dev branch. Let me do some test before merge.
Thank you

**Comment by gjhernandez1234** [comment]
Thanks, I'm actually doing tests with php7.2, I think if you should wait for the php-saml 3 stable version.

For the moment, it can be solved as mentioned in the issues: https://github.com/hslavich/OneloginSamlBundle/issues/52

**Pull request closed without merging**
