### PR TITLE
[FEATURE] have multiple idps

### PR DESCRIPTION
**Pull request by hhoechtl**
Relates #94

### CODE REVIEW

**Comment by hslavich** [comment]
How idp_mapping should be configured? I'm having issues testing SamlFactory

**Comment by hhoechtl** [comment]
An example would be:

`config/packages/dev/hslavich_saml_sp.yaml`:
```
hslavich_onelogin_saml:
  # Basic settings
  idps:
    keycloakeu:
      name: 'Keycloak EU'
      image: 'https://www.keycloak.org/resources/images/keycloak_logo_480x108.png'
      entityId: 'http://keycloak-eu.docker/auth/realms/master'
      singleSignOnService:
        url: 'http://keycloak-eu.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      singleLogoutService:
        url: 'http://keycloak-eu.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      x509cert: '%env(SAMLX509CERTEU)%'
    keycloakus:
      name: 'Keycloak US'
      image: 'https://www.keycloak.org/resources/images/keycloak_logo_480x108.png'
      entityId: 'http://keycloak-us.docker/auth/realms/master'
      singleSignOnService:
        url: 'http://keycloak-us.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      singleLogoutService:
        url: 'http://keycloak-us.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      x509cert: '%env(SAMLX509CERTUS)%'
    keycloakas:
      name: 'Keycloak AS'
      image: 'https://www.keycloak.org/resources/images/keycloak_logo_480x108.png'
      entityId: 'http://keycloak-as.docker/auth/realms/master'
      singleSignOnService:
        url: 'http://keycloak-as.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      singleLogoutService:
        url: 'http://keycloak-as.docker/auth/realms/master/protocol/saml'
        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      x509cert: '%env(SAMLX509CERTAS)%'
  sp:
    entityId: 'project'
    assertionConsumerService:
      url: 'http://project.docker/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      url: 'http://project.docker/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: 'MIIEoAIBAAKCAQEAjYPDsTqRfdSP1DrC+o5mOMaKlsh124LFuPZiJ4475zGLhGv0w4gYAmE4C7+yL5He499kgSATV8JBd4E8psfTTZGQK7/56GVSvx3xQksQlF3B6/Uibz3z7eXPEY0yZakrmUQsW4GYgi1plPRCs1AghF+L0EO3RIWBgkP7lT88eB6yziz+PUE2Md732JKjqXlxxMdDaLDbfCYwUO6/45JBK3LC2zvPTl3BX7FKNjQJb+tUWkY80MZqRcGc7Hg+gQKtE1mIQffLdzKl9mZ8oRF9IJxsm6u8NHMzJdzeVOTrVzkWGLM5kuuCKObkB+62fmHbwkK6/HbVrmpbn50hK733PwIDAQABAoIBAH78FcYbACMhck7Gy995mFCqGAJlrxxipHns3PcRsr8qvj79gI1UufaotloUkhgNlSx1cQJNfg3pykUqOvqNpRad3/jiM6ZOBYppm+wY36/C0hihx1x7A0AeT0k4oliHDRBjFEqoZ+moRm3bIV82L3eZJSSlHvbltejmiALM074UuDFkp75vxwRJDMOP5MTWhFI4iUmo+WinOGrtyOsK22z4+vfpCQllgsL1tll4Z6goJORW/GpNuLsctTne+qp0Wlh9pJAtrxf8UzR6kOrvWtpHYGZNgk6vKRYUlJEBMAoTmwU7rssQKacRfSTd/YTeBlOq4aXlaCijdwiwsGfjlQECgYEAw/uHUTRbCu/pXEp7BNEC1bHfBALM8eOWdqJ95zaoxsWtHAd9opIjM0Hx61mhDQUo51hvYJZ8ixn04sQtptKMYN3mRueMe+0xePALlo7snEaUGtHbcKQn3KWkAjgpzvTJkSqx64o5OQ+o91eYyVxqIYmp5+p/kX0shZ9XKM8mBVECgYEAuNodDT5Jx7Wl/iAGPcRjw6HPBNjodhLdYX6iNjZZwt6YqGPvwv7SIZBj2CBiXXjvJ3oBEKs3pR0mQuMlIrt0x4Dzh4Ao7+JpL1HdpNHARyk3HOYiuUeSqTAZeIXO6/+EJf4ZmGQm5QOr4lpWrpvo+4LN3/yoL9P/rKU90PjNT48CgYBy3Vo7Cu+NYn2onPKrKQF7U+v9AtMxto06bRRTzqJvFe7W7cEB5psA8NakdPzCj9KgfSGSP8ExGf6AZjDHhMHICGZuCko5XBTR6AcysAQXt/oYGgV+aIgAd4i/0EEYzjnRfm+XOIU/X2FNzqZ65lJB49iUV8l68R2GF5TTE04acQJ/BQ3xvWr2mX9eCpTVltrH35GNF5TWxmO9qezMgq75xVpQ0knpRGuzUzefg0lfZy7nWyz62nnUC6/AXBPZ8BkwGERuZEYc2HJYbfLPHLKfj1KRLzkbufU7DWVDTQhboBhchK1uBby3U4vGJ2pQ9HVO6ZGqD3XZI3WoiA/8oLos4wKBgECc8jSTIwmgwlyClx0F9/0X0MMBccOvxHErWRCS2iv97xUvQFLCNG5+3pNUt/0wCqlIRmdS03VfmKeK4Tz2g6oeUZcfwWeQWGKLp3WgNbyeb19z3zSJVMzPSuJyrPWH+z6BkFuPfxoqxXR1TXi4FS20MSk4iQKxWooiez35CutI'
  # Optional settings
  baseurl: 'http://project.docker/saml'
  strict: true
  debug: false
  security:
    nameIdEncrypted:       false
    authnRequestsSigned:   false
    logoutRequestSigned:   false
    logoutResponseSigned:  false
    wantMessagesSigned:    false
    wantAssertionsSigned:  false
    wantNameIdEncrypted:   false
    requestedAuthnContext: false
    signMetadata: false
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Tech User'
      emailAddress: 'techuser@example.com'
    support:
      givenName: 'Support User'
      emailAddress: 'supportuser@example.com'
  organization:
    en:
      name: 'master'
      displayname: 'Master'
      url: 'http://keycloak.docker'
```

`config/packages/security.yaml`:
```
security:
    providers:
        user_provider:
            # Loads user from user repository
            entity:
                class: 'App\Entity\User'
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        app:
            pattern:    ^/
            anonymous: true
            security: true
            saml:
                idp_mapping:
                    '/saml/login/keycloakeu': keycloakeu
                    '/saml/login/keycloakus': keycloakus
                    '/saml/login/keycloakas': keycloakas
                user_factory: App\Security\UserFactory
                persist_user: true
                check_path: /saml/acs
                login_path: /login
            logout:
                path: /saml/logout
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
```

**Comment by hslavich** [comment]
I think idp_mapping should not be required. We can use the idp key to generate the path. The feature is breaking compatibility in both configurations. I'll try to minimize this removing idp_maping

**Comment by hhoechtl** [comment]
Sure, this was just a quick solution to tackle the requirements of our customer

**Comment by guillaumepotier** [comment]
Hi guys,

I'm just seeing this PR and this is great news for us because we are looking to integrate SAMLv2 login in our application, for various distinct customers, and thus we need multiple idps. ([see my original stackoverflow question here](https://stackoverflow.com/questions/58855003/feasibility-to-implement-multi-tenant-saml-sso-on-a-php-symfony-3-x-api-backend)).

We initially were planning to create our own open source bundle (another one...) to address this issue since no other one seemed to be interested by this feature. I think it should be better for the Symfony community to minimise the number of similar bundles out there and we'd be interested to contribute here and help implementing this feature on this bundle.

How could we help there? How should we plan to support this while do not making BC breaks (or bumping major version with BC breaks inside?).

We'd be glad to support this change and make a PR once we're okay on the way to implement/configure it.

Best

**Comment by Navds** [comment]
@4rthem, do you have any idea why I got this using latest version of your branch **dev-fix-multiple-idp** ?
`Invalid audience for this Response (expected 'http://localhost/saml/metadata/default', got 'http://localhost/saml/metadata/idp1')`
I redirect to idp from /saml/login/idp1 then redirect binding to /saml/acs. I successfuly got a samlresponse but got stuck at /login with the above error.

**Pull request merged**
