### PR TITLE
Added missing responseUrl config option

### PR DESCRIPTION
**Pull request by JohnstonCode**
php-saml allows you to set `responseUrl` which is the location of the IdP where the SP will send the SLO Response to.

### CODE REVIEW

**Comment by JohnstonCode** [comment]
@hslavich

**Comment by JohnstonCode** [comment]
@a-menshchikov

**Comment by a-menshchikov** [comment]
@JohnstonCode retarget it onto 1.x please.

**Comment by JohnstonCode** [comment]
Done

**Comment by a-menshchikov** [comment]
@JohnstonCode I think Symfony 5.0 support should not be included in this PR.
Symfony 5.0 support already has been added in 2.x.

**Comment by JohnstonCode** [comment]
Sorry about that. Should be fixed now

**Comment by a-menshchikov** [comment]
@JohnstonCode thank you!

**Pull request merged**
